-- ══ EL PRESUPUESTO CONTRACTUAL SALE DEL CÓDIGO ══════════════════════════════
--
-- Las partidas del contrato vivían escritas en js/valPresupuesto.js: las 128
-- del contrato "RELAVERA R3 COTA 4416 · ETAPA 2 FASE 4" de ECOSERMO. Eso tiene
-- dos problemas y los dos se cobran caros.
--
-- El primero es el cliente siguiente: su contrato es otro, con otras partidas
-- y otros precios unitarios, y hoy eso sería editar el código y desplegar.
--
-- El segundo es este mismo cliente: los contratos tienen adendas. Cambiar un
-- precio unitario no debería pasar por un despliegue, y menos por uno que le
-- llega a la vez a todas las empresas.
--
-- ── Esta migración crea la tabla VACÍA ────────────────────────────────────
-- A propósito. Se aplica a la base de TODOS los clientes, y sembrar aquí el
-- presupuesto de ECOSERMO se lo metería a cada empresa nueva. El contrato de
-- cada una se carga aparte; el de ECOSERMO está en
-- sql/val_presupuesto_ecosermo.sql.
--
-- Mientras la tabla esté vacía, la aplicación usa el respaldo que sigue en
-- js/valPresupuesto.js. Es el mismo camino que se hizo con afp_tasas: la tabla
-- manda en cuanto tiene filas, y hasta entonces nada cambia.

create table if not exists public.val_presupuesto (
  id      bigint primary key generated by default as identity,

  -- El orden del documento. Sin esto la valorización sale con las partidas
  -- barajadas, que en un formato que el cliente firma no es un detalle.
  orden   int  not null,

  -- 's' sección (COSTO DIRECTO / INDIRECTO) · 'g' grupo · 'p' partida hoja
  t       text not null check (t in ('s','g','p')),

  item        text,              -- la numeración del contrato: '2.01.14.a'
  descripcion text not null,
  und         text,              -- hm · mes · vje · Und · %MO · %CD
  cant        numeric(14,4),     -- la cantidad contractual
  pu          numeric(14,4),     -- precio unitario, el que multiplica
  pres        numeric(16,2),     -- monto presupuestado
  niv         int,               -- nivel de sangría del grupo
  sec         text,              -- 'CD' o 'CI' en las filas de sección
  mod         int,               -- 1 = cuenta como mano de obra directa

  -- De dónde sale la CANTIDAD valorizada de esta partida:
  --   {"t":"manual"}                        la escribe el usuario
  --   {"t":"manual","sb":1}                 stand by, también a mano
  --   {"t":"eqHE","eq":"EXC ECOP-001"}      horas efectivas del equipo
  --   {"t":"eqMes","match":"CISTERNA..."}   incidencia mensual del equipo
  --   {"t":"cargo","cargo":"PEON"}          mes-hombre del cargo, del tareaje
  --   {"t":"pctMOD","pct":5}                % sobre la mano de obra directa
  --   {"t":"pctCD","pct":0.5}               % sobre el costo directo
  src     jsonb,

  creado_en timestamptz not null default now()
);

create unique index if not exists ux_val_presupuesto_orden
  on public.val_presupuesto (orden);

comment on table public.val_presupuesto is
  'Partidas del contrato para la valorizacion al cliente (formato VALEC). Vacia = se usa el respaldo de js/valPresupuesto.js.';
comment on column public.val_presupuesto.orden is
  'Orden del documento. Es unico: dos partidas en la misma posicion dejarian la valorizacion sin un orden estable.';
comment on column public.val_presupuesto.src is
  'De donde sale la cantidad valorizada. Ver el comentario del create table.';

-- RLS, igual que el resto: cerrado a quien no inició sesión. La migración que
-- cierra todo recorre pg_tables, pero eso ya corrió; esta tabla es nueva y hay
-- que dejarla cerrada aquí o nacería abierta.
alter table public.val_presupuesto enable row level security;

drop policy if exists val_presupuesto_authenticated on public.val_presupuesto;
create policy val_presupuesto_authenticated
  on public.val_presupuesto for all
  to authenticated
  using (true) with check (true);
