-- =====================================================================
--  GDARSystem · Panel de Liberación de Restricciones  (Operaciones)
--  Ejecutar en el SQL Editor de Supabase, de arriba hacia abajo.
--
--  NOTA SOBRE SEGURIDAD
--  Este esquema NO usa auth.users ni RLS con auth.uid(), a diferencia del
--  script original. GDARSystem no usa Supabase Auth: el login se resuelve
--  en el navegador contra el arreglo USERS de js/config.js y todas las
--  consultas viajan con la anon key, así que auth.uid() sería siempre NULL
--  y cualquier política basada en él bloquearía el tablero por completo.
--  El control de quién firma cada área se hace en el front (LIB_AREAS +
--  el campo lpAreas de cada usuario) y la trazabilidad queda en lib_bitacora,
--  que registra nombre, cargo y hora de cada cambio de estado.
--  Al final del archivo quedan las políticas RLS listas para el día que se
--  migre a Supabase Auth.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Actividades del tablero (una fila = una fila de la matriz)
-- ---------------------------------------------------------------------
create table if not exists lib_actividades (
  id             bigint primary key generated by default as identity,
  proy           text,                    -- código de proyecto (proyectos.codigo)
  frente         text not null default '',
  nombre         text not null default '',
  unidad         text,
  meta           numeric(14,2),
  ejecutor       text,                    -- ECOSERMO / Buenaventura / subcontrata
  semana_inicio  date not null,           -- lunes de la semana del tablero
  wbs_id         bigint,                  -- reservado: enlace futuro con lps_wbs
  cumplio        boolean,                 -- reservado: PPC al cierre de la semana
  causa_no_cump  text,
  creado_por     text,
  created_at     timestamptz not null default now()
);
create index if not exists ix_lib_act_semana on lib_actividades (semana_inicio);

-- ---------------------------------------------------------------------
-- 2. Requisitos / restricciones por área
-- ---------------------------------------------------------------------
create table if not exists lib_requisitos (
  id             bigint primary key generated by default as identity,
  act_id         bigint not null references lib_actividades(id) on delete cascade,
  area           text not null,           -- MAT, EQU, PER, CAL, OFT, SSO, PRO, CLI
  descripcion    text not null default '',
  estado         text not null default 'RES'
                   check (estado in ('RES','PRO','LIB','NA')),
  fecha_comp     date,                    -- fecha comprometida de liberación
  comentario     text,
  firmado_por    text,                    -- nombre del usuario GDAR que firmó
  firmado_cargo  text,
  firmado_at     timestamptz,
  created_at     timestamptz not null default now()
);
create index if not exists ix_lib_req_act  on lib_requisitos (act_id);
create index if not exists ix_lib_req_area on lib_requisitos (area, estado);

-- ---------------------------------------------------------------------
-- 3. Bitácora de cambios de estado
--    La escribe el front (no hay trigger con auth.uid() disponible).
-- ---------------------------------------------------------------------
create table if not exists lib_bitacora (
  id             bigint primary key generated by default as identity,
  req_id         bigint,
  act_nombre     text,
  area           text,
  descripcion    text,
  estado_de      text,
  estado_a       text,
  usuario        text,
  cargo          text,
  registrado_at  timestamptz not null default now()
);
create index if not exists ix_lib_bit_fecha on lib_bitacora (registrado_at desc);

-- ---------------------------------------------------------------------
-- 4. Vistas de apoyo (Power BI / consultas directas)
-- ---------------------------------------------------------------------
-- Estado calculado de cada actividad:
--   RES si alguna restringida · LIB si todas liberadas · si no PRO
create or replace view v_lib_actividad_estado as
select
  a.*,
  count(r.id) filter (where r.estado <> 'NA') as req_vigentes,
  count(r.id) filter (where r.estado = 'LIB') as req_liberados,
  count(r.id) filter (where r.estado = 'RES') as req_restringidos,
  case
    when count(r.id) filter (where r.estado <> 'NA') = 0 then 'NA'
    when count(r.id) filter (where r.estado = 'RES') > 0 then 'RES'
    when count(r.id) filter (where r.estado = 'LIB')
       = count(r.id) filter (where r.estado <> 'NA')     then 'LIB'
    else 'PRO'
  end as estado
from lib_actividades a
left join lib_requisitos r on r.act_id = a.id
group by a.id;

-- IRR por semana (requisitos liberados sobre requisitos vigentes)
create or replace view v_lib_kpi_semana as
select
  a.semana_inicio,
  count(*)                                  as actividades,
  count(*) filter (where a.estado = 'LIB')  as liberadas,
  count(*) filter (where a.estado = 'RES')  as restringidas,
  round(100.0 * sum(a.req_liberados) / nullif(sum(a.req_vigentes),0), 1) as irr_pct
from v_lib_actividad_estado a
group by a.semana_inicio
order by a.semana_inicio desc;

-- Cuello de botella: qué área traba más frentes
create or replace view v_lib_carga_area as
select r.area,
       count(*) filter (where r.estado = 'RES') as restringidos,
       count(*) filter (where r.estado = 'PRO') as en_proceso,
       count(*) filter (where r.estado = 'LIB') as liberados
from lib_requisitos r
group by r.area
order by restringidos desc;

-- ---------------------------------------------------------------------
-- 5. Realtime (opcional): el tablero se refresca en las demás pantallas
--    Descomentar solo si más adelante se suscribe el front al canal.
-- ---------------------------------------------------------------------
-- alter publication supabase_realtime add table lib_requisitos;
-- alter publication supabase_realtime add table lib_actividades;

-- ---------------------------------------------------------------------
-- 6. RLS — DEJAR COMENTADO mientras el login siga siendo el de js/config.js
--    Habilitar solo después de migrar a Supabase Auth, o el panel deja de
--    funcionar para todos.
-- ---------------------------------------------------------------------
-- alter table lib_actividades enable row level security;
-- alter table lib_requisitos  enable row level security;
-- alter table lib_bitacora    enable row level security;
--
-- create policy lib_lectura on lib_actividades for select using (auth.role() = 'authenticated');
-- create policy lib_req_lectura on lib_requisitos for select using (auth.role() = 'authenticated');
-- create policy lib_bit_lectura on lib_bitacora for select using (auth.role() = 'authenticated');
